Hepsi: Node.o Iterator.o FileReader.o CircularDoublyLinkedList.o ListCreator.o Test.o Calistir
	g++ ./lib/Node.o ./lib/Iterator.o ./lib/FileReader.o ./lib/CircularDoublyLinkedList.o ./lib/ListCreator.o ./lib/Test.o -o ./bin/odev
Node.o:
	g++ -I "./include/" -c ./src/Node.cpp -o ./lib/Node.o
Iterator.o:
	g++ -I "./include/" -c ./src/Iterator.cpp -o ./lib/Iterator.o
FileReader.o:
	g++ -I "./include/" -c ./src/FileReader.cpp -o ./lib/FileReader.o
CircularDoublyLinkedList.o:
	g++ -I "./include/" -c ./src/CircularDoublyLinkedList.cpp -o ./lib/CircularDoublyLinkedList.o
ListCreator.o:
	g++ -I "./include/" -c ./src/ListCreator.cpp -o ./lib/ListCreator.o
Test.o:
	g++ -I "./include/" -c ./src/Test.cpp -o ./lib/Test.o
Calistir:
	./bin/odev
